"""Update models according to requirements

Revision ID: 217e8389fd0e
Revises: 2025_11_26_educreds
Create Date: 2025-12-14 20:42:39.626240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '217e8389fd0e'
down_revision: Union[str, None] = '2025_11_26_educreds'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('teacher_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc+3', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc+3', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('student_journal',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'journal_id')
    )
    op.add_column('grades', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.add_column('grades', sa.Column('journal_id', sa.Integer(), nullable=False))
    op.add_column('grades', sa.Column('number_value', sa.SmallInteger(), nullable=True))
    op.add_column('grades', sa.Column('is_mark', sa.Boolean(), nullable=False))
    op.add_column('grades', sa.Column('is_pass', sa.Boolean(), nullable=False))
    op.add_column('grades', sa.Column('is_valid_pass', sa.Boolean(), nullable=False))
    op.add_column('grades', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc+3', now())"), nullable=False))
    op.alter_column('grades', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('grades', 'value',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_grades_subject_id'), table_name='grades')
    op.create_index('idx_user_journal_date', 'grades', ['user_id', 'journal_id', 'date'], unique=False)
    op.create_index('idx_user_lesson', 'grades', ['id', 'user_id'], unique=False)
    op.create_index(op.f('ix_grades_journal_id'), 'grades', ['journal_id'], unique=False)
    op.create_index(op.f('ix_grades_user_id'), 'grades', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_lesson_journal', 'grades', ['id', 'user_id', 'journal_id'])
    op.create_unique_constraint(None, 'grades', ['id'])
    op.drop_constraint(op.f('grades_subject_id_fkey'), 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'journals', ['journal_id'], ['id'])
    op.create_foreign_key(None, 'grades', 'users', ['user_id'], ['id'])
    op.drop_column('grades', 'subject_id')
    op.drop_column('grades', 'type_')
    op.drop_column('grades', 'comment')
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.execute('DROP TABLE subjects CASCADE')
    op.execute("CREATE TYPE synctype AS ENUM ('MANUAL', 'AUTO', 'WATCH_MODE')")
    op.add_column('sync_logs', sa.Column('sync_type', sa.Enum('MANUAL', 'AUTO', 'WATCH_MODE', name='synctype'), nullable=False))
    op.add_column('sync_logs', sa.Column('new_grades_count', sa.Integer(), nullable=True))
    op.add_column('sync_logs', sa.Column('updated_grades_count', sa.Integer(), nullable=True))
    op.add_column('sync_logs', sa.Column('message', sa.String(length=500), nullable=True))
    op.add_column('sync_logs', sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc+3', now())"), nullable=False))
    op.alter_column('sync_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
    op.drop_column('sync_logs', 'grades_count')
    op.drop_column('sync_logs', 'timestamp')
    op.drop_column('sync_logs', 'error_msg')
    op.add_column('users', sa.Column('edu_login_encrypted', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('edu_user_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('group_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('group_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_authenticated', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('notification_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('morning_notification_enabled', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('morning_notification_time', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('watch_mode_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('watch_mode_last_sync_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc+3', now())"), nullable=False))
    op.create_index('idx_group_edu_user', 'users', ['id', 'group_id'], unique=False)
    op.create_index('idx_group_id', 'users', ['group_id'], unique=False)
    op.create_index('idx_telegram_id', 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_group_id'), 'users', ['group_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.drop_column('users', 'student_id')
    op.drop_column('users', 'referrer')
    op.drop_column('users', 'edu_username_encrypted')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'username')
    op.drop_column('users', 'is_suspicious')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'last_sync')
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('users', 'is_block')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_block', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('notifications_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_suspicious', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('edu_username_encrypted', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('referrer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_group_id'), table_name='users')
    op.drop_index('idx_telegram_id', table_name='users')
    op.drop_index('idx_group_id', table_name='users')
    op.drop_index('idx_group_edu_user', table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'watch_mode_last_sync_at')
    op.drop_column('users', 'watch_mode_expires_at')
    op.drop_column('users', 'morning_notification_time')
    op.drop_column('users', 'morning_notification_enabled')
    op.drop_column('users', 'notification_enabled')
    op.drop_column('users', 'is_authenticated')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'group_name')
    op.drop_column('users', 'group_id')
    op.drop_column('users', 'edu_user_id')
    op.drop_column('users', 'edu_login_encrypted')
    op.add_column('sync_logs', sa.Column('error_msg', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('sync_logs', sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc+3'::text, now())"), autoincrement=False, nullable=False))
    op.add_column('sync_logs', sa.Column('grades_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.alter_column('sync_logs', 'status',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('sync_logs', 'created_at')
    op.drop_column('sync_logs', 'message')
    op.drop_column('sync_logs', 'updated_grades_count')
    op.drop_column('sync_logs', 'new_grades_count')
    op.drop_column('sync_logs', 'sync_type')
    op.execute("DROP TYPE synctype")
    op.add_column('grades', sa.Column('comment', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('type_', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('grades', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key(op.f('grades_subject_id_fkey'), 'grades', 'subjects', ['subject_id'], ['id'])
    op.drop_constraint(None, 'grades', type_='unique')
    op.drop_constraint('uq_user_lesson_journal', 'grades', type_='unique')
    op.drop_index(op.f('ix_grades_user_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_journal_id'), table_name='grades')
    op.drop_index('idx_user_lesson', table_name='grades')
    op.drop_index('idx_user_journal_date', table_name='grades')
    op.create_index(op.f('ix_grades_subject_id'), 'grades', ['subject_id'], unique=False)
    op.alter_column('grades', 'value',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('grades', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('grades', 'updated_at')
    op.drop_column('grades', 'is_valid_pass')
    op.drop_column('grades', 'is_pass')
    op.drop_column('grades', 'is_mark')
    op.drop_column('grades', 'number_value')
    op.drop_column('grades', 'journal_id')
    op.drop_column('grades', 'user_id')
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('teacher', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc+3'::text, now())"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subjects_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subjects_pkey')),
    sa.UniqueConstraint('user_id', 'code', name=op.f('unique_user_subject_code'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    op.drop_table('student_journal')
    op.drop_table('journals')
    # ### end Alembic commands ###
