"""add edu creds to user

Revision ID: 2025_11_26_educreds
Revises: c67b204d61fa
Create Date: 2025-11-26
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_11_26_educreds'
down_revision: Union[str, None] = 'c67b204d61fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('edu_username_encrypted', sa.String(), nullable=True))
    op.add_column('users', sa.Column('edu_password_encrypted', sa.String(), nullable=True))
    op.add_column('users', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_sync', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('users', 'last_sync')
    op.drop_column('users', 'student_id')
    op.drop_column('users', 'edu_password_encrypted')
    op.drop_column('users', 'edu_username_encrypted')
    # ### end Alembic commands ###
